// ============================================
// Solana Wallet Tracker — Discord Alert Bot
// Auto-generated by The Trading Room Setup
// ============================================
// Deploy free on Railway.app or Render.com
// ============================================

const express = require("express");
const app = express();
app.use(express.json());

// ─── CONFIG ───────────────────────────────
const DISCORD_WEBHOOK = "https://discord.com/api/webhooks/1511240475292467331/Vho3RZaRJeXTc8GThwhrhYbrRV5MDrtcguzp3CWpEOmFmGcWcWvoZW_JPKE1wCoIBYCI";
const TRACKED_WALLETS = [
  {
    "address": "AQ45HqCk5uKNFD7LS7sumRs91G3XbscB4zjg1pxMW7A9",
    "label": "wanka wahale"
  }
];
// ──────────────────────────────────────────

// Health check — keeps Railway happy and confirms the app is alive
app.get("/", (req, res) => {
  res.status(200).json({ status: "ok", service: "solana-wallet-tracker" });
});

// Helius sends a POST here whenever a tracked wallet transacts
app.post("/webhook", async (req, res) => {
  res.sendStatus(200); // Acknowledge immediately
  const events = req.body;
  if (!Array.isArray(events)) {
    console.error("Webhook received non-array body:", typeof req.body, req.body);
    return;
  }

  for (const event of events) {
    try {
      await handleTransaction(event);
    } catch (e) {
      console.error("Error handling event:", e.message, e.stack);
    }
  }
});

async function handleTransaction(event) {
  const { signature, type, tokenTransfers, nativeTransfers, feePayer, timestamp } = event;
  if (!signature) return;

  // Find which tracked wallet triggered this
  const wallet = TRACKED_WALLETS.find(w =>
    feePayer === w.address ||
    (nativeTransfers || []).some(t => t.fromUserAccount === w.address || t.toUserAccount === w.address) ||
    (tokenTransfers || []).some(t => t.fromUserAccount === w.address || t.toUserAccount === w.address)
  );

  const walletLabel = wallet ? wallet.label : shortenAddress(feePayer);
  const txTime = timestamp ? new Date(timestamp * 1000).toUTCString() : "now";

  let embed = null;

  // ── SWAP / DEX trade ──
  if (type === "SWAP" && tokenTransfers && tokenTransfers.length >= 2) {
    const sold = tokenTransfers.find(t => t.fromUserAccount === feePayer);
    const bought = tokenTransfers.find(t => t.toUserAccount === feePayer);

    if (sold && bought) {
      const soldAmt = formatAmount(sold.tokenAmount);
      const boughtAmt = formatAmount(bought.tokenAmount);
      const soldSym = sold.mint === "So11111111111111111111111111111111111111112" ? "SOL" : shortenMint(sold.mint);
      const boughtSym = bought.mint === "So11111111111111111111111111111111111111112" ? "SOL" : shortenMint(bought.mint);

      embed = {
        title: "🟢  SWAP DETECTED",
        color: 0x1db954,
        fields: [
          { name: "Wallet", value: `**${walletLabel}** (`+shortenAddress(feePayer)+`)`, inline: false },
          { name: "Sold", value: `${soldAmt} ${soldSym}`, inline: true },
          { name: "Bought", value: `${boughtAmt} ${boughtSym}`, inline: true },
          { name: "Time", value: txTime, inline: false },
          { name: "Transaction", value: `[View on Solscan](https://solscan.io/tx/${signature})`, inline: false },
        ],
        footer: { text: "The Trading Room • Wallet Tracker" },
        timestamp: new Date().toISOString(),
      };
    }
  }

  // ── SOL Transfer ──
  if (!embed && type === "TRANSFER" && nativeTransfers && nativeTransfers.length > 0) {
    const transfer = nativeTransfers[0];
    const lamports = transfer.amount || 0;
    const sol = (lamports / 1e9).toFixed(4);
    const direction = transfer.toUserAccount === feePayer ? "RECEIVED" : "SENT";
    const color = direction === "RECEIVED" ? 0x378add : 0xe24b4a;

    embed = {
      title: direction === "RECEIVED" ? "📥  SOL RECEIVED" : "📤  SOL SENT",
      color,
      fields: [
        { name: "Wallet", value: `**${walletLabel}** (`+shortenAddress(feePayer)+`)`, inline: false },
        { name: "Amount", value: `${sol} SOL`, inline: true },
        { name: direction === "RECEIVED" ? "From" : "To", value: shortenAddress(direction === "RECEIVED" ? transfer.fromUserAccount : transfer.toUserAccount), inline: true },
        { name: "Transaction", value: `[View on Solscan](https://solscan.io/tx/${signature})`, inline: false },
      ],
      footer: { text: "The Trading Room • Wallet Tracker" },
      timestamp: new Date().toISOString(),
    };
  }

  if (embed) {
    await sendDiscordAlert(embed);
  }
}

async function sendDiscordAlert(embed) {
  const res = await fetch(DISCORD_WEBHOOK, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ embeds: [embed] }),
  });
  if (!res.ok) console.error("Discord webhook failed:", res.status);
}

function shortenAddress(addr) {
  if (!addr) return "unknown";
  return addr.slice(0, 4) + "..." + addr.slice(-4);
}

function shortenMint(mint) {
  return mint ? mint.slice(0, 4) + "..." + mint.slice(-4) : "???";
}

function formatAmount(amount) {
  if (!amount) return "0";
  const n = parseFloat(amount);
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(2) + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(2) + "K";
  return n.toFixed(4);
}

const PORT = process.env.PORT || 3000;
try {
  app.listen(PORT, () => {
    console.log(`✅ Wallet tracker running on port ${PORT}`);
  }).on("error", (err) => {
    console.error("❌ Server failed to start:", err.message, err.stack);
    process.exit(1);
  });
} catch (err) {
  console.error("❌ Fatal error starting server:", err.message, err.stack);
  process.exit(1);
}

// ─── PROCESS-LEVEL ERROR GUARDS ───────────
process.on("uncaughtException", (err) => {
  console.error("❌ Uncaught exception:", err.message, err.stack);
  process.exit(1);
});

process.on("unhandledRejection", (reason, promise) => {
  console.error("❌ Unhandled promise rejection at:", promise, "reason:", reason);
  process.exit(1);
});
